/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui.WorkArea.Student.CourseWork;

import Model.Directory.CourseRegistration.StudentCourseRegDirectory;
import Model.Registration.StudentRegistration;
import javax.swing.JPanel;

/**
 *
 * @author Saurabh Vyawahare
 */
public class StudentCourseWorkTableViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentCourseWorkViewJPanel
     */
    public StudentCourseWorkTableViewJPanel() {
        initComponents();
    }

    StudentCourseWorkTableViewJPanel(JPanel WorkArea, StudentRegistration studentReg, StudentCourseRegDirectory studentCourseRegList) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAdmissionYear = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        txtAdmissionYear = new javax.swing.JTextField();
        ComSemester = new javax.swing.JComboBox<>();
        txtProgram = new javax.swing.JTextField();
        lblCourse1 = new javax.swing.JLabel();
        ComCourse1 = new javax.swing.JComboBox<>();
        lblCourse2 = new javax.swing.JLabel();
        ComCourse2 = new javax.swing.JComboBox<>();
        txtTotalCredits = new javax.swing.JTextField();
        lblTotalCredits = new javax.swing.JLabel();
        lblLifetimeCredits = new javax.swing.JLabel();
        txtLifetimeCredits = new javax.swing.JTextField();
        lblProgram = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Course Work View");

        lblAdmissionYear.setText("Admission Year");

        lblSemester.setText("Semester");

        txtAdmissionYear.setEnabled(false);
        txtAdmissionYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdmissionYearActionPerformed(evt);
            }
        });

        ComSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2023", "Spring 2024", "Fall 2024", "Spring 2025" }));
        ComSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComSemesterActionPerformed(evt);
            }
        });

        txtProgram.setEnabled(false);

        lblCourse1.setText("Course 1");

        ComCourse1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Application Modeling and Design", "Data Science Engineering Methods and Tools", "Web Design and User Experience Engineering", "Neural Modeling Methods and Tools","Program Structure and Algorithms","Business Analysis and Information Engineering","Web Development Tools and Methods","Software Quality Control and Management" }));

        lblCourse2.setText("Course 2");

        ComCourse2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Application Modeling and Design", "Data Science Engineering Methods and Tools", "Web Design and User Experience Engineering", "Neural Modeling Methods and Tools","Program Structure and Algorithms","Business Analysis and Information Engineering","Web Development Tools and Methods","Software Quality Control and Management"}));

        txtTotalCredits.setEnabled(false);

        lblTotalCredits.setText("Total Credits ");

        lblLifetimeCredits.setText("Lifetime Credits ");

        txtLifetimeCredits.setEnabled(false);

        lblProgram.setText("Program");

        btnSave.setText("Save");

        btnUpdate.setText("Update");

        btnBack.setText("<< Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAdmissionYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalCredits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLifetimeCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalCredits)
                            .addComponent(txtAdmissionYear)
                            .addComponent(txtLifetimeCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProgram)
                            .addComponent(lblCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProgram, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComCourse1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComCourse2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(273, 273, 273))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(ComSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgram)
                    .addComponent(txtProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse1)
                    .addComponent(ComCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCourse2)
                    .addComponent(ComCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmissionYear)
                    .addComponent(txtAdmissionYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalCredits))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLifetimeCredits)
                    .addComponent(txtLifetimeCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdmissionYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdmissionYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdmissionYearActionPerformed

    private void ComSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComSemesterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComCourse1;
    private javax.swing.JComboBox<String> ComCourse2;
    private javax.swing.JComboBox<String> ComSemester;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAdmissionYear;
    private javax.swing.JLabel lblCourse1;
    private javax.swing.JLabel lblCourse2;
    private javax.swing.JLabel lblLifetimeCredits;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCredits;
    private javax.swing.JTextField txtAdmissionYear;
    private javax.swing.JTextField txtLifetimeCredits;
    private javax.swing.JTextField txtProgram;
    private javax.swing.JTextField txtTotalCredits;
    // End of variables declaration//GEN-END:variables
}
